'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const C=require('../js/core.js'),{createIO}=require('../js/io.js');
const io=createIO(),encode=(text,encoding='utf-8',bom=false)=>Buffer.concat([Buffer.from(bom?(encoding==='utf-8'?[239,187,191]:encoding==='utf-16le'?[255,254]:[254,255]):[]),Buffer.from(io.encode(text,encoding))]);
function dat(headers,rows,{encoding='utf-8',bom=false,eol='\r\n',trailing=true,name='source.dat'}={}){const text=[headers,...rows].map(C.compose).join(eol)+(trailing?eol:'');return new File([encode(text,encoding,bom)],name);}
function confirm(f){f.reviewSignature=C.fieldSignature(f);return f;}
function field(name,rule,id=name){return confirm({id,name,note:'Synthetic test rule',rule:{scope:'all',...rule}});}
function copies(headers){return headers.map((h,i)=>field(h,{op:'copy',source:i}));}
async function setup(headers,rows,fields,groups=[],files=[],opts={}){const source=dat(headers,rows,opts),engine=C.createEngine(opts),info=await engine.inspect(source),spec={version:1,key:0,fields:fields||copies(headers),groups};const p=await engine.preflight(source,spec,files,info.hash);return {source,engine,info,spec,...p};}
async function build(p){const parts=[],result=await p.engine.transform(p.plan,b=>parts.push(Buffer.from(b)));const bytes=Buffer.concat(parts),output=new File([bytes],'delivery.dat');const verified=await p.engine.verify(p.plan,output,result);return {bytes,output,result,verified};}
async function group(name,ids,fields,clear=[]){const file=new File(['ID\r\n'+ids.join('\r\n')+'\r\n'],name+'.csv'),info=await io.listScan(file),actions=Object.fromEntries(fields.map(f=>[f.id,clear.includes(f.id)?'clear':'keep']));return {file,spec:{name,key:'ID',actions,loadedHash:info.hash}};}
test('incremental SHA-256 matches independent Node crypto at padding and chunk boundaries',()=>{for(const n of [0,1,55,56,63,64,65,127,128,129,10000,1048580]){const bytes=Buffer.alloc(n);for(let i=0;i<n;i++)bytes[i]=i%251;const h=io.hash();for(let at=0;at<n;at+=37)h.update(bytes.subarray(at,at+37));assert.equal(h.hex(),crypto.createHash('sha256').update(bytes).digest('hex'));}});
for(const encoding of ['utf-8','utf-16le','utf-16be'])for(const bom of (encoding==='utf-8'?[false,true]:[true]))for(const eol of ['\r\n','\n','\r'])for(const trailing of [true,false]){
  test(`exact preservation ${encoding} BOM=${bom} EOL=${JSON.stringify(eol)} trailing=${trailing}`,async()=>{const p=await setup(['ID','Unicode','Empty','Space'],[['00001','김 / 😀 / e\u0301','','  a\tB  '],['00002','Å','','']],null,[],[],{encoding,bom,eol,trailing,chunkBytes:3});assert.ok(p.report.valid);const b=await build(p);assert.deepEqual(b.bytes,Buffer.from(await p.source.arrayBuffer()));assert.equal(b.verified.rows,2);assert.equal(b.verified.outputHash,crypto.createHash('sha256').update(b.bytes).digest('hex'));});
}
test('client mapping: rename, reorder, source reuse and explicit blank with independent expected bytes',async()=>{const p=await setup(['ID','A','B'],[['001','00123','한글'],['002','','x']],[field('Document ID',{op:'copy',source:0}),field('Renamed B',{op:'copy',source:2}),field('B again',{op:'copy',source:2}),field('A',{op:'copy',source:1}),field('Blank',{op:'blank',source:null})]);const b=await build(p);const expected=dat(['Document ID','Renamed B','B again','A','Blank'],[['001','한글','한글','00123',''],['002','x','x','','']]);assert.deepEqual(b.bytes,Buffer.from(await expected.arrayBuffer()));});
test('all screenshot Delivery Work types produce independently specified output',async()=>{const headers=['ID','Last','First','Names','Type','Sent','Received','Created','Modified','Page','Placeholder','Redaction','Parent'];
 const rows=[['P1','Kim','Jane','Jane Kim;John Doe','Mail','2026-10-01 13:04:05','01/10/2026 14:05:06','10/01/2026 01:02:03 PM','2026-10-01T16:07:08','4','No','True',''],['C1','Doe','John','John Doe','IM','2026-10-02 00:00:00','02/10/2026 00:00:01','10/02/2026 12:00:00 AM','2026-10-02T00:00:00','','Slip','False','P1']];
 const fields=[field('ID',{op:'copy',source:0}),field('Attachment Count',{op:'children',parent:12,mode:'direct',writeTo:'every'}),field('Custodian',{op:'name',last:1,first:2,empty:'error'}),field('All Custodians',{op:'list-map',source:3,pairs:[['Jane Kim','Kim, Jane'],['John Doe','Doe, John']],delimiter:';',unknown:'error',empty:'error'}),field('Item Type',{op:'map',source:4,pairs:[['Mail','Email'],['IM','Chat']],unknown:'error',empty:'error'}),...[[5,'YYYY-MM-DD HH:mm:ss'],[6,'DD/MM/YYYY HH:mm:ss'],[7,'MM/DD/YYYY hh:mm:ss A'],[8,'YYYY-MM-DDTHH:mm:ss']].map(([source,format])=>field(headers[source],{op:'datetime',source,format,outputFormat:'MM/DD/YYYY HH:mm',empty:'error'})),field('Page Count',{op:'pages',source:9,flag:10,placeholder:['Slip']}),field('Confidentiality',{op:'constant',value:'CONFIDENTIAL'}),field('Redacted',{op:'map',source:11,pairs:[['True','Y'],['False','N']],unknown:'error',empty:'error',yn:true})];
 const p=await setup(headers,rows,fields),b=await build(p);const expected=dat(fields.map(f=>f.name),[['P1','1','Kim, Jane','Kim, Jane;Doe, John','Email','10/01/2026 13:04','10/01/2026 14:05','10/01/2026 13:02','10/01/2026 16:07','4','CONFIDENTIAL','Y'],['C1','0','Doe, John','Doe, John','Chat','10/02/2026 00:00','10/02/2026 00:00','10/02/2026 00:00','10/02/2026 00:00','1','CONFIDENTIAL','N']]);assert.deepEqual(b.bytes,Buffer.from(await expected.arrayBuffer()));
 // Nonzero seconds dropped by the HH:MM ticket format are counted for review (P1: 4 dates, C1: Received 00:00:01).
 assert.equal(p.report.secondsDropped,5);
});
test('date output: ticket HH:MM drops seconds without rounding; seconds are never invented',()=>{
 assert.equal(C.formatDate('2026-12-31 23:59:59','YYYY-MM-DD HH:mm:ss','MM/DD/YYYY HH:mm'),'12/31/2026 23:59');
 assert.equal(C.formatDate('2026-12-31 23:59:59','YYYY-MM-DD HH:mm:ss','MM/DD/YYYY HH:mm:ss'),'12/31/2026 23:59:59');
 assert.equal(C.formatDate('12/31/2026 12:05 AM','MM/DD/YYYY hh:mm A','MM/DD/YYYY HH:mm'),'12/31/2026 00:05');
 assert.equal(C.formatDate('2026-01-02 07:08','YYYY-MM-DD HH:mm','MM/DD/YYYY HH:mm'),'01/02/2026 07:08');
 assert.throws(()=>C.formatDate('2026-01-02 07:08','YYYY-MM-DD HH:mm','MM/DD/YYYY HH:mm:ss'),/not invented/);
 assert.throws(()=>C.formatDate('2026-01-02 07:08:09','YYYY-MM-DD HH:mm:ss',undefined),/output date format/);
 assert.throws(()=>C.formatDate('2026-01-02','YYYY-MM-DD HH:mm','MM/DD/YYYY HH:mm'),/date-only/);
 const f={name:'Sent',rule:{op:'datetime',scope:'all',source:0,format:'YYYY-MM-DD HH:mm',outputFormat:'MM/DD/YYYY HH:mm:ss',empty:'error'}};
 assert.throws(()=>C.checkField(f,['Sent'],[]),/not invented/);
});
test('Redacted Y/N: blanks cannot be preserved; an explicit blank mapping is honored',async()=>{
 const yn=extra=>field('Redacted',{op:'map',source:1,pairs:[['True','Y'],['False','N']],unknown:'error',yn:true,...extra});
 assert.throws(()=>C.checkField(yn({empty:'keep'}),['ID','R'],[]),/cannot preserve blanks/);
 const blocked=await setup(['ID','R'],[['A','']],[field('ID',{op:'copy',source:0}),yn({empty:'error'})]);assert.equal(blocked.report.exceptionCount,1);
 const mapped=await setup(['ID','R'],[['A',''],['B','True']],[field('ID',{op:'copy',source:0}),yn({empty:'error',pairs:[['True','Y'],['','N']]})]),b=await build(mapped);
 assert.deepEqual(b.bytes,Buffer.from(await dat(['ID','Redacted'],[['A','N'],['B','Y']]).arrayBuffer()));
});
test('editor-time field check rejects incomplete rules before preflight',()=>{
 const h=['ID','Page','Flag'];
 assert.throws(()=>C.checkField({name:'Page Count',rule:{op:'pages',scope:'all',source:1,flag:2,placeholder:['']}},h,[]),/nonempty placeholder/);
 assert.throws(()=>C.checkField({name:'X',rule:{op:'copy',scope:'group',group:'Gone',source:1}},h,['Email']),/scope group is missing/);
 assert.throws(()=>C.checkField({name:' ',rule:{op:'blank',scope:'all'}},h,[]),/blank/);
 assert.equal(C.checkField({name:'Page Count',rule:{op:'pages',scope:'all',source:1,flag:2,placeholder:['Slip']}},h,[]).name,'Page Count');
});
test('group scrubbing after Delivery Work; scoped constant copies source outside scope',async()=>{const fields=[field('ID',{op:'copy',source:0}),field('Status',{op:'constant',value:'CONFIDENTIAL',source:1,scope:'group',group:'Email'}),field('Secret',{op:'copy',source:2})],g=await group('Email',['A'],fields,['Secret']);const p=await setup(['ID','Status','Secret'],[['A','old','sensitive'],['B','other','keep']],fields,[g.spec],[g.file]);const b=await build(p);assert.deepEqual(b.bytes,Buffer.from(await dat(['ID','Status','Secret'],[['A','CONFIDENTIAL',''],['B','other','keep']]).arrayBuffer()));assert.equal(p.report.matched,1);});
test('overlapping identical groups accepted; conflicting rules rejected',async()=>{const fields=copies(['ID','A']),a=await group('Email',['A'],fields,['A']),b=await group('Other',['A'],fields,['A']);const p=await setup(['ID','A'],[['A','x']],fields,[a.spec,b.spec],[a.file,b.file]);assert.equal(p.report.overlap,1);b.spec.actions.A='keep';await assert.rejects(setup(['ID','A'],[['A','x']],fields,[a.spec,b.spec],[a.file,b.file]),/Conflicting/);});
test('targets not in source and duplicate targets fail closed',async()=>{const f=copies(['ID','A']),g=await group('Email',['missing'],f);await assert.rejects(setup(['ID','A'],[['A','x']],f,[g.spec],[g.file]),/absent/);const d=await group('Dup',['A','A'],f);await assert.rejects(setup(['ID','A'],[['A','x']],f,[d.spec],[d.file]),/duplicate target/);});
test('child direct / descendant counts and roots-only placement',async()=>{const fields=[field('ID',{op:'copy',source:0}),field('Direct',{op:'children',parent:1,mode:'direct',writeTo:'every'}),field('Desc',{op:'children',parent:1,mode:'descendants',writeTo:'roots'})],p=await setup(['ID','Parent'],[['P',''],['C','P'],['G','C']],fields),b=await build(p);assert.deepEqual(b.bytes,Buffer.from(await dat(['ID','Direct','Desc'],[['P','1','2'],['C','1',''],['G','0','']]).arrayBuffer()));});
for(const [name,rows]of [['missing parent',[['A','Z']]],['self parent',[['A','A']]],['cycle',[['A','B'],['B','A']]]])test('child count blocks '+name,async()=>{await assert.rejects(setup(['ID','Parent'],rows,[field('ID',{op:'copy',source:0}),field('Count',{op:'children',parent:1,mode:'direct',writeTo:'every'})]),/absent|Self-parent|Cycle/);});
test('unknown values, missing names and blank page counts are exceptions, not successful outputs',async()=>{for(const rule of [{op:'map',source:1,pairs:[['True','Y']],empty:'error',unknown:'error',yn:true},{op:'pages',source:1,flag:2,placeholder:['Y']},{op:'name',last:1,first:2,empty:'error'}]){const p=await setup(['ID','Value','Flag'],[['A','','']], [field('ID',{op:'copy',source:0}),field('Converted',rule)]);assert.equal(p.plan,null);assert.equal(p.report.valid,false);assert.equal(p.report.exceptionCount,1);}});
test('exception report is bounded but total remains exact',async()=>{const rows=Array.from({length:75},(_,i)=>['A'+i,'unknown']),p=await setup(['ID','Type'],rows,[field('ID',{op:'copy',source:0}),field('Type',{op:'map',source:1,pairs:[['Known','Email']],empty:'error',unknown:'error'})]);assert.equal(p.report.exceptionCount,75);assert.equal(p.report.exceptions.length,40);assert.equal(p.report.omittedExceptions,35);});
test('calendar validity and dates never use ambient timezone or Date parser',()=>{const S='MM/DD/YYYY HH:mm:ss';assert.equal(C.formatDate('2024-02-29 23:59:59','YYYY-MM-DD HH:mm:ss',S),'02/29/2024 23:59:59');for(const v of ['2023-02-29 10:00:00','2026-04-31 10:00:00','2026-01-01 24:00:00','2026-01-01 10:00:60','2026-01-01T10:00:00Z','2026-01-01 10:00:00.001','2026-01-01'])assert.throws(()=>C.formatDate(v,'YYYY-MM-DD HH:mm:ss',S),/Invalid calendar|does not match/);assert.equal(C.formatDate('01/02/2026 00:00:00','DD/MM/YYYY HH:mm:ss',S),'02/01/2026 00:00:00');assert.throws(()=>C.formatDate('13/01/2026 00:00 PM','MM/DD/YYYY hh:mm A','MM/DD/YYYY HH:mm'),/Invalid|does not match/);});
test('no implicit trimming, case folding, empty-to-N, duplicate name removal or sorting',async()=>{const fields=[field('ID',{op:'copy',source:0}),field('Names',{op:'list-map',source:1,pairs:[['Z','Zed, Z'],[' A','Alpha, A']],delimiter:';',empty:'error',unknown:'error'})],p=await setup(['ID','Names'],[['A','Z; A;Z']],fields),b=await build(p);assert.ok(b.bytes.toString().includes('Zed, Z;Alpha, A;Zed, Z'));const q=await setup(['ID','Names'],[['A','z']],fields);assert.equal(q.report.valid,false);});
test('unreviewed / stale field signature, unmapped field, duplicate headers and removed identity rejected',async()=>{const p=await setup(['ID','A'],[['A','x']]);const f=structuredClone(p.spec.fields);delete f[1].reviewSignature;await assert.rejects(p.engine.preflight(p.source,{...p.spec,fields:f},[],p.info.hash),/Review/);f[1]=confirm({...p.spec.fields[1],rule:{op:'copy',scope:'all',source:99}});await assert.rejects(p.engine.preflight(p.source,{...p.spec,fields:f},[],p.info.hash),/valid source/);f[1]=confirm({...p.spec.fields[1],name:'ID'});await assert.rejects(p.engine.preflight(p.source,{...p.spec,fields:f},[],p.info.hash),/duplicate/);await assert.rejects(p.engine.preflight(p.source,{...p.spec,fields:[p.spec.fields[1]]},[],p.info.hash),/identity/);});
test('output field reordering invalidates category field coverage unless rule IDs remain complete',async()=>{const fields=copies(['ID','A']),g=await group('Email',['A'],fields),p=await setup(['ID','A'],[['A','x']],fields,[g.spec],[g.file]);const newField=field('B',{op:'copy',source:1});await assert.rejects(p.engine.preflight(p.source,{...p.spec,fields:[...fields,newField]},[g.file],p.info.hash),/every output field/);});
test('malformed DAT, mixed EOL, decoding failures and unsupported encodings rejected',async()=>{const eng=C.createEngine();for(const bytes of [Buffer.from('þIDþ\u0014þAþ\nþAþ\n'),Buffer.from('þIDþ\nþAþ\r\n'),Buffer.from('þIDþ\nþAþ\n\n'),Buffer.from([0xff,0xfe,0,0,65,0,0,0]),Buffer.from([0xc3,0x28]),Buffer.from([0xff,0xfe,0xfe,0,10,0,0,0xd8])])await assert.rejects(eng.inspect(new File([bytes],'bad.dat')));});
test('duplicate / empty / whitespace / scientific-notation identity blocked',async()=>{for(const rows of [[['A','x'],['A','y']],[['','x']],[[' A','x']],[['1E10','x']]])await assert.rejects(setup(['ID','A'],rows),/identity|Duplicate|Bates|notation/);});
test('same-size corruption, row reordering, truncation and altered header rejected by saved-file reread',async()=>{const p=await setup(['ID','A'],[['A','x'],['B','y']]),b=await build(p);for(const text of [b.bytes.toString().replace('þxþ','þzþ'),[C.compose(['ID','A']),C.compose(['B','y']),C.compose(['A','x']),''].join('\r\n'),b.bytes.toString().slice(0,-4),b.bytes.toString().replace('þIDþ','þZZþ')])await assert.rejects(p.engine.verify(p.plan,new File([text],'bad.dat'),b.result));});
test('source snapshot mismatch and target snapshot mismatch rejected',async()=>{const p=await setup(['ID','A'],[['A','x']]);await assert.rejects(p.engine.preflight(p.source,p.spec,[],'0'.repeat(64)),/changed since/);const g=await group('Email',['A'],p.spec.fields);g.spec.loadedHash='0'.repeat(64);await assert.rejects(p.engine.preflight(p.source,{...p.spec,groups:[g.spec]},[g.file],p.info.hash),/target file changed/);});
test('target file replacement after preflight blocks output',async()=>{const fields=copies(['ID','A']),g=await group('Email',['A'],fields),p=await setup(['ID','A'],[['A','x']],fields,[g.spec],[g.file]);p.plan.files[0]=new File(['ID\r\nB\r\n'],'Email.csv');await assert.rejects(p.engine.transform(p.plan,async()=>{}),/Target list changed/);});
test('backpressure is respected: only one output emission may be pending',async()=>{const rows=Array.from({length:1500},(_,i)=>['A'+i,'x'.repeat(1000)]),p=await setup(['ID','A'],rows);let active=0,max=0,parts=0;await p.engine.transform(p.plan,async()=>{active++;max=Math.max(max,active);parts++;await new Promise(r=>setTimeout(r,1));active--;});assert.equal(max,1);assert.ok(parts>=2);});
test('strict CSV quoted fields and DAT target files',async()=>{const f=new File(['ID,Text\r\nA,"a,b\r\nc"\r\nB,"a""b"\r\n'],'list.csv'),rows=[];const inf=await io.listScan(f,r=>rows.push(r));assert.equal(inf.count,2);assert.deepEqual(rows,[['A','a,b\r\nc'],['B','a"b']]);for(const text of ['ID,A\nX,"unclosed','ID,A\nX,"done"junk','ID,A\nX,a,b'])await assert.rejects(io.listScan(new File([text],'bad.csv')));assert.equal((await io.listScan(dat(['ID'],[['A']]))).format,'DAT');});
test('pasted tables fail atomically and preserve exact names',()=>{assert.deepEqual(C.parseHeaders(' A \tB'),[' A ','B']);assert.throws(()=>C.parseHeaders('A\nA'));assert.throws(()=>C.parsePairs('a\tb\na\tc'));assert.throws(()=>C.parsePairs('a\tb\tc'));const f=copies(['ID','A']);assert.deepEqual(C.parseScrubRules('ID\tPopulate\nA\tScrub',f,'named','Populate','Scrub','review').actions,{ID:'keep',A:'clear'});assert.throws(()=>C.parseScrubRules('ID\tPopulate\nA\t?',f,'named','Populate','Scrub','review'));assert.throws(()=>C.parseScrubRules('Populate\n',f,'ordered','Populate','Scrub','review'));});
test('standalone validation derives expected digest from the approved plan',async()=>{const p=await setup(['ID','A'],[['A','x']]),b=await build(p),expected=await p.engine.expectedDigest(p.plan);assert.deepEqual(expected,b.result);assert.equal((await p.engine.verify(p.plan,b.output,expected)).status,'PASS');});
test('large metadata roundtrip and unselected-column corruption are never ignored',async()=>{const p=await setup(['ID','Discarded','Selected'],[['A','😀'.repeat(10000),'keep']],[field('ID',{op:'copy',source:0}),field('Selected',{op:'copy',source:2})],[],[],{chunkBytes:7});assert.ok(p.report.valid);await build(p);const bad=new File(['þIDþ\u0014þDiscardedþ\u0014þSelectedþ\nþAþ\u0014þbadþinsideþ\u0014þkeepþ\n'],'bad.dat');await assert.rejects(p.engine.inspect(bad));});
test('published synthetic samples: job is valid and expected output matches the engine and independent spot checks',async()=>{const fs=require('node:fs'),path=require('node:path'),S=require('./make-samples.cjs');
 const source=new File([fs.readFileSync(path.join(S.dir,'sample-source.dat'))],'sample-source.dat'),engine=C.createEngine(),info=await engine.inspect(source),job=JSON.parse(fs.readFileSync(path.join(S.dir,'sample-job.json'),'utf8'));
 assert.equal(job.sourceHash,info.hash);const {output,report}=await S.expected(engine,source,info);assert.deepEqual(output,fs.readFileSync(path.join(S.dir,'sample-expected-output.dat')));assert.equal(report.exceptionCount,0);
 const rows=output.toString('utf8').replace(/^﻿/,'').split('\r\n').filter(Boolean).map(r=>io.splitDAT(r)),head=rows[0],get=(id,name)=>rows.find(r=>r[0]===id)[head.indexOf(name)];
 assert.equal(head.length,13);assert.equal(get('SYN000001','Attachment Count'),'2');assert.equal(get('SYN000006','Page Count'),'1');assert.equal(get('SYN000009','Item Type'),'Calendar Item');assert.equal(get('SYN000001','Email Date Sent'),'03/02/2026 09:15');assert.equal(get('SYN000004','Email Date Sent'),'');assert.equal(get('SYN000007','All Custodians'),'');assert.equal(get('SYN000001','All Custodians'),'Rivera, Ana;Okafor, Ben');assert.equal(get('SYN000004','Redacted'),'Y');
 for(const text of [JSON.stringify(job),fs.readFileSync(path.join(S.dir,'sample-source.dat'),'utf8')])assert.match(text,/SYN/);
});
