'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..');
test('runtime has no network clients, remote dependencies, HTML injection sinks or persistent data storage',()=>{const sources=['js/io.js','js/core.js','js/worker.js','js/app.js'].map(p=>fs.readFileSync(path.join(root,p),'utf8')).join('\n');assert.doesNotMatch(sources,/\bfetch\s*\(|XMLHttpRequest|WebSocket|sendBeacon|importScripts|localStorage|sessionStorage|indexedDB|\.innerHTML\s*=/);const html=fs.readFileSync(path.join(root,'index.html'),'utf8');assert.match(html,/connect-src 'none'/);assert.match(html,/worker-src blob:/);assert.match(html,/form-action 'none'/);assert.doesNotMatch(html,/(?:src|href)=["']https?:/);assert.doesNotMatch(html,/<script[^>]*>\s*[^<\s]/);});
// The baseline is the local C:\Coding\Tools workspace. Inside a Git repository (e.g. phlee219/eDiscovery) the parent
// holds separately versioned copies, so the check runs only with LEGACY_DIR or a non-repository parent folder.
const legacyDir=process.env.LEGACY_DIR||(fs.existsSync(path.join(root,'..','.git'))?null:path.join(root,'..'));
test('baseline files remain byte-for-byte untouched when available in parent workspace',{skip:legacyDir?false:'parent is a Git repository; set LEGACY_DIR to check the local baseline'},()=>{for(const b of JSON.parse(fs.readFileSync(path.join(root,'docs/legacy-baseline.json'),'utf8'))){const p=path.join(legacyDir,b.name);if(!fs.existsSync(p)){assert.ok(!process.env.LEGACY_DIR,'missing '+p);continue;}const bytes=fs.readFileSync(p);assert.equal(bytes.length,b.bytes);assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),b.sha256);}});
test('every referenced first-party runtime asset exists',()=>{const html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const m of html.matchAll(/(?:src|href)="([^"#]+)"/g)){if(m[1].startsWith('data:')||m[1]==='./')continue;assert.ok(fs.existsSync(path.join(root,m[1])),m[1]);}});
test('samples are explicitly synthetic and deployment does not require a backend or package install',()=>{assert.equal(JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8')).dependencies,undefined);assert.ok(fs.existsSync(path.join(root,'.nojekyll')));});
test('git ignore rules exclude test downloads, business-data file types and release archives; published samples are synthetic',()=>{const ignore=fs.readFileSync(path.join(root,'.gitignore'),'utf8').split(/\r?\n/);for(const rule of ['test-results/','release/','*.zip','*.dat','*.csv','*.audit.json','production-job*.json'])assert.ok(ignore.includes(rule),rule);
 // Published as a subfolder of phlee219/eDiscovery with branch-based Pages; a nested workflow would be ignored by GitHub.
 assert.equal(fs.existsSync(path.join(root,'.github')),false);
 for(const f of fs.readdirSync(path.join(root,'samples')))assert.match(f,/^sample-/,f);});
